name: Azure Infrastructure Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: Deploy Bicep to Azure
      run: |
        az deployment group create --resource-group rg-novahr --template-file ./infrastructure.bicep
