name: Azure Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies
      working-directory: ./nova-hr/novahr.client
      run: npm install

    - name: Build React App
      working-directory: ./nova-hr/novahr.client
      run: npm run build

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep to Azure
      run: |
        az deployment group create --resource-group rg-novahr --template-file ./nova-hr/infrastructure.bicep

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: novahr-webapp
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./nova-hr/novahr.client/build